### ISSUE TITLE
TypeError with example

### ISSUE THREAD

**Issue by ghost** [mbr/svglue#4]
I get this Traceback when I try the example

```
$ python3 example.py
Traceback (most recent call last):
  File "example.py", line 22, in <module>
    src = str(tpl)
TypeError: __str__ returned non-string (type bytes)
```

**Comment by mbr** [comment]
Fixed. Example works now. If you could test the remaining functions as well and give me a go-ahead, I'll push another release.

**Comment by mbr** [comment]
On closer inspection (aka while rebasing) I noticed that all these things had already been fixed by @ticktronaut, just not released yet. I'll put a release out.

As it turns out, Python2 backwards compatibility just became a little less important -- CairoSVG seems to have issues on Python2 anyway.

**Comment by mbr** [comment]
`0.3.0` released.

**Comment by Mega-Touk** [comment]
I still have this problem with `0.3.0`

tested with
`src = tpl.__str__()`
and
`src = str(tpl)`
on the example.py

Python 3.4.3

**Comment by Mega-Touk** [comment]
@mbr Do you know any fix ? did i do something wrong ?

**Comment by recursiveElk** [comment]
Still an issue in 0.3.0

**Comment by mbr** [comment]
Please check if 90d3f01 fixes the issue for you.

Unfortunately, recent PyPI changes broke all my release tooling =/. If the current version works, I'll try to release 0.4.0

**Comment by brianmcdonald** [comment]
Still an issue on the current version with Python 3.6.4.

**Comment by polclota** [comment]
Try `src = tpl.__str__().decode()`. It worked for me with Python 3.9.9 Windows 10
